version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: c2dreport-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "chat_reports"
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql