version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: c2dreport-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "chat_reports"
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: c2dreport-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_VHOST=/